### ISSUE TITLE
User invitations

### ISSUE THREAD

**Issue by cainwatson** [tuning-fork/boilerplate#412]
## 🚀 What new feature do you want to see?

We want to add the ability for admin users to invite other users to organizations. 

https://www.figma.com/file/cydfN0jAlrF5aQEIkLQ4Zd/Boilerplate-(Copy)?node-id=813%3A17110

## 🎯 Acceptance Criteria

1. As a creator of an organization, I should be marked as the admin.
2. As an admin I can invite users to an organization I am in.
   * From the User Index page, the admin should be able to enter the email of the person they'd like invite
   * The person should receive an email with a link to setup their account and be added to the org
   * *If the person doesn't use the link within a certain amount of time, the invite should expire and the admin must re-invite them*
3. As an admin I can uninvite users from an organization.
   * If an admin decides they manually want to expire an open invitation for a user, they should be able to click a button on the user index page.
   * If the person tries to click the link in the email after it has expired, they should see a page telling them it. (No account creation possible)
4. As an admin I can remove users from an organization. 
   * If a person was successfully invited and added to an organization, an admin should be able to click a button on the user index page that removes them from the org
   * ~~The removed user should get an email letting them know this happened~~

## 🤔 Implementation Details

Overview of things to do:
* Save roles for an organization (possibly under organization_users table)

Resources:
  * https://github.com/varvet/pundit # not a fan of the magic, but like the explicit policies
  * https://github.com/be9/acl9
  * https://github.com/RolifyCommunity/rolify # i like this
  * https://github.com/chaps-io/access-granted
  * https://www.culttt.com/2016/01/20/implementing-roles-and-permissions-in-ruby-on-rails
  * https://www.osohq.com/post/role-based-access-control-rbac-ruby

**Comment by cainwatson** [comment]
Blocked by https://github.com/Jess-White/boilerplate/issues/234

**Comment by cainwatson** [comment]
## Tasks

* [x] Add "roles" column to organization users table (string array)
* [x] In the organization create controller, make sure to set the creator's role
  to 'admin'
* [x] Default organization user roles to ['user'] if not given
* [x] Create "organization_invitations" table + model
  * "email"
  * "organization_id"
  * "user_id"
  * "token"
  * "expires_at"
  * "first_name"
  * "last_name"
* [x] Create API for organization invitations
    ```
    ## VIEW INVITES FLOW:
    GET /organizations/:id/invitations

    200 OK
    [
      {...}
    ]

    ## INVITE FLOW:
    POST /organizations/:id/invitations
    {
      email: "test@example.com",
      first_name: "Chidi",
      last_name: "Anagonye",
    }

    ## ACCEPT INVITATION FLOW:
    POST /organizations/:id/invitations/:invitation_id/accept
    {
      token: "abc",
      email: "test@example.com",
      first_name: "Chidi",
      last_name: "Anagonye",
    }

    201 Created
    {...}

    ## RE-INVITE FLOW:
    PATCH /organizations/:id/invitations/:invitation_id/re-invite

    200 Updated
    {...}

    ## UN-INVITE FLOW:
    DELETE /organizations/:id/invitations/:invitation_id

    200 Deleted
    {...}

    ## REMOVE USER FLOW:
    DELETE /organizations/:id/users/:user_id

    200 Deleted
    {...}
    ```
    * create invitation should schedule a job that sends the email
    * re-invite should schedule a job that sends the email
    * remove user should schedule a job that sends the email
* [x] Add authorization implementation
  * Implement some sort of policy framework like Pundit
  * Add for endpoints:
    * admins of orgs should only be able to use invitations endpoints
    * admins of orgs should only be able to remove users from org
    * ? maybe won't need organization_users#create
* [x] Head over to frontend to add those UI changes
  * Add button for "Invite User" with modal
  * Add page for users who click the invitation link in their email (similar to
    password reset page)
  * Have "tabs" for users and invitations
  * Fetch invitations, display in table, add icons to the beginning depending on
    whether the invitation has expired or is pending
  * Add icon button for uninviting an invitation
  * Add icon button for re-inviting an invitation that has expired
  * Add icon button for removing a user
* [x] Create ticket for admins to be able to make others admins

**Comment by cainwatson** [comment]
frontend

~~0. Check if organization_users#create is being used or not~~
   * if not remove on backend
   * if so, remove on frontend and then backend
~~0.5 Check if organization_users#show is being used or not~~
   * why? how? does it to be?
1. add a new tab for the user page that shows invitations
   * fetch invitations from api through a new invitations service
2. create a popover reuseable component
   * used for when you hover over the buttons and icons
3. implement revinvite icon-button in invitations table
4. implement unvinvite icon-button in invitations table
5. implement remove user icon-button in user table
6. implement invite user button 
   * only available to admins
   * create some modal with the form fields
7. implement icons in invitations table
   * expired
   * pending
8. follow up on giving frontend ability to know if current user is an admin and
   hiding users link from sidebar if not an admin
8. follow up on restricting organization user methods on backend (index)
